pipeline:
  name: Pipeline
  identifier: Pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags:
    ai_generated: ""
  properties:
    ci:
      codebase:
        connectorRef: DataOps_Github
        repoName: Test_GIT
        build: <+input>
  stages:
    - stage:
        name: Test_Stage
        identifier: Test_Stage
        description: ""
        type: CI
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: Docker_REG
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: Docker_REG
                    image: kalyanachakravarthi76/harness:3.10
                    shell: Sh
                    command: |-
                      echo "Installing dependencies if requirements.txt exists..."
                      echo "Running Python script..."
                      python3 trigger_dataflow.py
                      echo "Python script completed successfully!"